name: Apple Setup Certs

description: Installs Apple certificates in temporary keychain

inputs:
  # Required
  certificate-base64:
    description: "Base64 version of apple certificate.p12"
    required: true
  certificate-password:
    description: "Password required to import decoded certificate"
    required: true

  # Optional
  certificate-name:
    description: "Name of decoded certificate file. Extension is always .p12"
    required: false
    default: "certificate"
  keychain-db-name:
    description: "Name of temporary keychain db. Extension is always .keychain-db"
    required: false
    default: "signing"
  keychain-password:
    description: "Password for the temporary keychain database, random password will be used if not set"
    required: false

runs:
  using: composite
  steps:
    - name: Generate keychain password (if not provided)
      shell: bash -e
      run: |
        if [ -z "${{ inputs.keychain-password }}" ]; then
          keychain_password=$(uuidgen | cut -c 1-16)
          echo "::set-output name=keychain_password::$keychain_password"
        fi

    - name: Create variables
      shell: bash -e
      run: |
        CERTIFICATE_PATH="$RUNNER_TEMP/${{ inputs.certificate-name }}.p12"
        KEYCHAIN_PATH="$RUNNER_TEMP/${{ inputs.keychain-db-name }}.keychain-db"
    
    - name: Decode and save certificate
      shell: bash
      run: |
        echo -n "${{ inputs.certificate-base64 }}" | base64 --decode -o $CERTIFICATE_PATH

    - name: Create temporary keychain
      shell: bash -e
      run: |
        security create-keychain -p "${{ steps.generate_keychain_password.outputs.keychain_password }}" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "${{ steps.generate_keychain_password.outputs.keychain_password }}" $KEYCHAIN_PATH

    - name: Import certificate to keychain
      shell: bash -e
      run: |
        security import $CERTIFICATE_PATH -P "${{ inputs.certificate-password }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "${{ steps.generate_keychain_password.outputs.keychain_password }}" $KEYCHAIN_PATH

    - name: List keychain contents (for verification)
      shell: bash -e
      run: |
        security list-keychain -d user -s $KEYCHAIN_PATH

    - name: Cleanup
      shell: bash -e
      run: |
        rm -f $CERTIFICATE_PATH
