name: Apple Delete Provisioning Profile

description: Deletes Provisioning Profile

inputs:
  provisioning-profile-name:
    description: "Name of provisioning profile file. Extension is always .mobileprovision"
    required: false
    default: "provisioning_profile"

runs:
  using: composite
  steps:
    - name: Delete provisioning profile
      shell: bash -e
      run: rm ~/Library/MobileDevice/Provisioning\ Profiles/${{ inputs.provisioning-profile-name }}.mobileprovision
