name: CI

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - reopened
      - opened
      - edited

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr-title:
    name: Validate PR Title
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Validate semantic PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          scopes: |
            DM-CI-\d+

  changelog-testing:
    name: Changelog Testing
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: "0.3.9"
          toTag: "0.3.8"
          writeToFile: false

      - name: Print the changelog
        run: cat "${{ steps.changelog.outputs.changes }}"
