name: CI

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - reopened
      - opened
      - edited

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr-title:
    name: Validate PR Title
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Validate semantic PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            bug
            feat
            feature
            docs
            doc
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: true
          scopes: |
            DM-CI-\d+
            
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6.2.2
        with:
          toTag: "989f0dbdb445e03e83a8e7aeb0faa6ec83621504"
          # fromTag: "241504386993cbed77068ece0844450200f7141f"
          configuration: .github/changelog-configuration.json
          # Match optional release candidate tags (e.g., 1.2.3-rc1)
          configurationJson: |
              {
              }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Outputs
        env:
          GENERATED_CHANGELOG: ${{ steps.build_changelog.outputs.changelog }}
        run: |
          echo "Generated Changelog:"
          echo "$GENERATED_CHANGELOG"

