name: Deploy PreProd

on:
  push:
    branches:
      - release/[0-9]*.[0-9]*.[0-9]*

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-and-changelog:
    name: Calculate Version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      build-name: ${{ steps.rc_calculator.outputs.build_name }}
      build-number: ${{ github.run_number }}
      changelog: ${{ steps.build_changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch and Calculate RC Version
        id: rc_calculator
        run: |
          git fetch --tags --prune --quiet
          
          BRANCH_NAME="${{ github.ref_name }}"
          BASE_VERSION="${BRANCH_NAME#release/}"
          echo "Extracted Base Version: $BASE_VERSION"
          
          LATEST_RC_TAG=$(git tag -l "${BASE_VERSION}-rc.*" | sort -V | tail -n 1)
          
          if [ -z "$LATEST_RC_TAG" ]; then
            echo "No previous release candidates found for v${BASE_VERSION}. Starting at rc.1"
            NEXT_RC=1
          else
            echo "Found latest existing tag: $LATEST_RC_TAG"
            CURRENT_RC=$(echo "$LATEST_RC_TAG" | sed 's/.*-rc\.//')
            NEXT_RC=$((CURRENT_RC + 1))
          fi
          
          COMPUTED_TAG="${BASE_VERSION}-rc.${NEXT_RC}"
          echo "Target Release Candidate Tag: $COMPUTED_TAG"
          echo "build_name=$COMPUTED_TAG" >> $GITHUB_OUTPUT

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          toTag: ${{ github.sha }}
          configuration: .github/changelog-configuration.json
          # Match optional release candidate tags (e.g., 1.2.3-rc1)
          configurationJson: |
            {
              "tag_resolver":{
                  "filter":{
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+(-rc\\.[0-9]+)?$",                 
                  }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
  deploy:
    name: Deploy to PreProd
    needs: version-and-changelog
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: PreProd
    steps:
      - name: Deploy to PreProd
        run: echo "Deploying to PreProd environment..."

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.version-and-changelog.outputs.build-name }}
          name: Release Candidate ${{ needs.version-and-changelog.outputs.build-name }}
          body: ${{ needs.version-and-changelog.outputs.changelog }}
          target_commitish: ${{ github.sha }}
          prerelease: true
          make_latest: true
