on:
  workflow_call

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        uses: damian-molinski/dm-ci/actions/greet@master

      - name: Goodbye World
        uses: damian-molinski/dm-ci/actions/goodbay@master
