name: Android Setup Keystore
description: Creates keystore.jks and keystore.properties
inputs:
  # Use GitHub Secrets for keystore
  keystore-base64:
    description: "Base64 version of keystore"
    required: true

  # Use GitHub Secrets for passwords and alias
  store-password:
    description: "Store password for keystore"
    required: true
  key-password:
    description: "Key password for keystore"
    required: true
  key-alias:
    description: "Key alias for keystore"
    required: true

  # Optional
  keystore-name:
    description: "Name of keystore files"
    required: false
    default: "upload-keystore.jks"
  keystore-properties-name:
    description: "Name of keystore properties files"
    required: false
    default: "keystore.properties"
  directory:
    description: "Relevant path where to create keystore and its properties"
    required: false
    default: "android/app"

runs:
  using: composite
  steps:
    - name: Set keystore and keystore-properties path variables
      shell: bash
      run: |
        echo "KEYSTORE_PATH=${{ inputs.directory }}/${{ inputs.keystore-name }}" >> $GITHUB_ENV
        echo "KEYSTORE_PROPERTIES_PATH=${{ inputs.directory }}/${{ inputs.keystore-properties-name }}" >> $GITHUB_ENV

    - name: Ensure dir exists
      shell: bash
      run: mkdir -p ${{ inputs.directory }}

    - name: Create keystore
      shell: bash
      run: |
        touch "$KEYSTORE_PATH"
        echo "${{ inputs.keystore-base64 }} | base64 -d" > "$KEYSTORE_PATH" || exit 1  # Exit on failure

    - name: Create keystore properties
      shell: bash
      run: |
        touch $KEYSTORE_PROPERTIES_PATH
        echo "storePassword=${{ inputs.store-password }}" >> $KEYSTORE_PROPERTIES_PATH
        echo "keyPassword=${{ inputs.key-password }}" >> $KEYSTORE_PROPERTIES_PATH
        echo "keyAlias=${{ inputs.key-alias }}" >> $KEYSTORE_PROPERTIES_PATH
        echo "storeFile=$keystore-path" >> $KEYSTORE_PROPERTIES_PATH
